# Generated by Django 5.1.1 on 2024-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('Professional', 'PROFESSIONAL'), ('Niche', 'NICHE'), ('business', 'BUSINESS'), ('educational', 'EDUCATIONAL'), ('technology', 'TECHNOLOGY'), ('lifestyle', 'LIFESTYLE'), ('Review', 'REVIEW'), ('Creative', 'CREATIVE'), ('News', 'NEWS'), ('others', 'OTHERS')], max_length=20, null=True),
        ),
    ]
